### ISSUE TITLE
update release

### ISSUE THREAD

**Issue by aldiserg** [pomerium/cli#179]
Can you update release from the main branch?
new features need to be released
thank's =)

**Comment by desimone** [comment]
👋 @aldiserg 

What features were you looking for? 

Typically, we try to bump new features along with a new minor release, and only update patches for bug fixes and security issues.

**Comment by aldiserg** [comment]
@desimone 

https://github.com/pomerium/cli/pull/164 is the most important thing

also all packages/images update is important
thank's =)

**Comment by desimone** [comment]
Until we cut an official minor, can you try https://github.com/pomerium/cli/releases/tag/v0.21.0-beta

**Comment by aldiserg** [comment]
yeap, thank you a lot =)
