### ISSUE TITLE
"pomerium-cli -v" is not working to figure out installed version

### ISSUE THREAD

**Issue by cluettig** [pomerium/cli#51]
## What happened?
Pomerium CLI Version 0.17.1 is not providing proper version via `pomerium-cli -v`  or `pomerium-cli --version`
## What did you expect to happen?
`pomerium-cli -v`  or `pomerium-cli --version` is returning correct version of Pomerium CLI
## How'd it happen?
1. run `pomerium-cli -v` or `pomerium-cli --version`
2. cli shows following
![image](https://user-images.githubusercontent.com/45224537/162146474-b1dc10ce-2e04-47be-aeda-49e9ec95c219.png)

## What's your environment like?
- Pomerium version (retrieve with `pomerium --version`): 0.17.1
- Server Operating System: Windows 10

## Additional comment
Doesn't allow easy Analysis of user reports in case of Issues with Pomerium and Pomerium CLI

**Comment by alexfornuto** [comment]
Confirmed.

**Comment by wasaga** [comment]
@sherifkayad https://github.com/pomerium/cli/releases/tag/v0.17.2
