### ISSUE TITLE
Unable to install pomerium-cli on Apple M1 by using Homebrew

### ISSUE THREAD

**Issue by kahoulei** [pomerium/cli#86]
## What happened?

Following the installation doc but I get this error:

```
% brew tap pomerium/tap
==> Tapping pomerium/tap
Cloning into '/opt/homebrew/Library/Taps/pomerium/homebrew-tap'...
remote: Enumerating objects: 444, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 444 (delta 20), reused 9 (delta 5), pack-reused 405
Receiving objects: 100% (444/444), 63.01 KiB | 418.00 KiB/s, done.
Resolving deltas: 100% (124/124), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/pomerium/homebrew-tap/Formula/pomerium.rb
formulae require at least a URL
Error: Cannot tap pomerium/tap: invalid syntax in tap!
```

## What did you expect to happen?

pomerium-cli should be installed

## How'd it happen?

1. Ran `brew tap pomerium/tap`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by kahoulei** [comment]
i think pomerium (not CLI) is missing arm support? https://github.com/pomerium/homebrew-tap/blob/master/Formula/pomerium.rb#L10-L19

**Comment by calebdoxsey** [comment]
You can now tap and install the CLI.
